swagger: '2.0'
basePath: "/"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Uzytkownik'
definitions:
  Uzytkownik:
    type: object
    required:
      - Id
    properties:
      Id:
        type: integer
        format: int64
      Imię:
        type: string
      Nazwisko:
        type: string
      Login:
        type: string
      Hasło:
        type: string
        format: password
      Email:
        type: string
        format: email
      Galerie:
        type: array
        items:
          $ref: '#/definitions/Galeria'
      Sesje:
        type: array
        items:
          $ref: '#/definitions/Sesja'
  Galeria:
    type: object
    required:
      - Id
    properties:
      Id:
        type: integer
        format: int64
      Tytul:
        type: string
      Opis:
        type: string
      Data:
        type: string
      Widocznosc:
        type: string
      Tagi:
        type: array
        items:
          $ref: '#/definitions/Tag'
      Obrazy:
        type: array
        items:
          $ref: '#/definitions/Obraz'
      Uzytkownik:
        $ref: '#/definitions/Uzytkownik'
  Sesja:
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Token:
        type: integer
      Waznosc:
        type: string
        format: date
      Uzytkownik:
        $ref: ../definitions/Uzytkownik
  Administrator:
    type: object
    properties:
      Uzytkownik:
        $ref: ../definitions/Uzytkownik
      Prawa:
        type: integer
  Tag:
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Tekst:
        type: string
      Galerie:
        type: array
        items:
          $ref: '#/definitions/Galeria'
      Obrazy:
        type: array
        items:
          $ref: ../definitions/Obrazy
  Obraz:
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Tytul:
        type: string
      Opis:
        type: string
      Data:
        type: string
        format: date
      Nazwa pliku:
        type: string
      Sciezka:
        type: string
      Rozmiar:
        type: string
      Galeria:
        $ref: '#/definitions/Galeria'
      Komentarze:
        type: array
        items:
          $ref: '#/definitions/Komentarz'
      Tagi:
        type: array
        items:
          $ref: '#/definitions/Tag'
  Miniatura:
    type: object
    properties:
      Typ:
        type: string
      Obraz:
        $ref: '#/definitions/Obraz'
  Komentarz:
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Tresc:
        type: string
      Data:
        type: string
        format: date
      Obraz:
        $ref: '#/definitions/Komentarz'
